### ISSUE TITLE
bug in count_by_vhost - doesn't filter by 'active'

### ISSUE THREAD

**Issue by MattMacGillivray** [btoic/aptop#10]
aptop doesn't actually filter by active vhost, rather, it displays all vhosts (active or not).  Looking at the code, I found the problem on line 155 of ApacheStatus.py:
https://github.com/modulec/aptop/blob/master/ApTop/ApacheStatus.py#L155

Looks like you've fixed this in bitbucket, but the yum install seems to pull this version.

``` python
        vstatus = {}
        if self.active:
            vhosts = self.filter_active(data)
        else:
            vhosts = data
        # BUG: filter by method is ignoring the results of filter_active
        vhosts = self.filter_http_methods(data)
```

should be:

``` python
        vstatus = {}
        if self.active:
            vhosts = self.filter_active(data)
        else:
            vhosts = data

        # FIX: use the results of filter_active
        vhosts = self.filter_http_methods(vhosts)
```

Awesome tool btw!

**Comment by btoic** [comment]
So, better late then never heh?

Tnx for the report, yes you are right, the filtering was only done correctly in grouped vhost by url screen.
This should now be fixed and available from the main branch untl next pypi release
